package entity;
// Generated Aug 11, 2020 12:45:06 PM by Hibernate Tools 4.3.1



/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private int id;
     private Student student;
     private Double gradeE;
     private Double gradeIm;
     private Double gradeP;

    public Grade() {
    }

	
    public Grade(int id) {
        this.id = id;
    }

    public Grade(Student student, Double gradeE, Double gradeIm, Double gradeP) {
        this.student = student;
        this.gradeE = gradeE;
        this.gradeIm = gradeIm;
        this.gradeP = gradeP;
    }
    
    
    public Grade(int id, Student student, Double gradeE, Double gradeIm, Double gradeP) {
       this.id = id;
       this.student = student;
       this.gradeE = gradeE;
       this.gradeIm = gradeIm;
       this.gradeP = gradeP;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Double getGradeE() {
        return this.gradeE;
    }
    
    public void setGradeE(Double gradeE) {
        this.gradeE = gradeE;
    }
    public Double getGradeIm() {
        return this.gradeIm;
    }
    
    public void setGradeIm(Double gradeIm) {
        this.gradeIm = gradeIm;
    }
    public Double getGradeP() {
        return this.gradeP;
    }
    
    public void setGradeP(Double gradeP) {
        this.gradeP = gradeP;
    }




}


