package entity;
// Generated Aug 11, 2020 12:45:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String idSt;
     private String nameSt;
     private String emailSt;
     private String phoneNumberSt;
     private boolean sexSt;
     private String addressSt;
     private String imageSt;
     private Set grades = new HashSet(0);

    public Student() {
    }

	
    public Student(String idSt, String nameSt, String emailSt, String phoneNumberSt, boolean sexSt, String addressSt, String imageSt) {
        this.idSt = idSt;
        this.nameSt = nameSt;
        this.emailSt = emailSt;
        this.phoneNumberSt = phoneNumberSt;
        this.sexSt = sexSt;
        this.addressSt = addressSt;
        this.imageSt = imageSt;
    }
    public Student(String idSt, String nameSt, String emailSt, String phoneNumberSt, boolean sexSt, String addressSt, String imageSt, Set grades) {
       this.idSt = idSt;
       this.nameSt = nameSt;
       this.emailSt = emailSt;
       this.phoneNumberSt = phoneNumberSt;
       this.sexSt = sexSt;
       this.addressSt = addressSt;
       this.imageSt = imageSt;
       this.grades = grades;
    }
   
    public String getIdSt() {
        return this.idSt;
    }
    
    public void setIdSt(String idSt) {
        this.idSt = idSt;
    }
    public String getNameSt() {
        return this.nameSt;
    }
    
    public void setNameSt(String nameSt) {
        this.nameSt = nameSt;
    }
    public String getEmailSt() {
        return this.emailSt;
    }
    
    public void setEmailSt(String emailSt) {
        this.emailSt = emailSt;
    }
    public String getPhoneNumberSt() {
        return this.phoneNumberSt;
    }
    
    public void setPhoneNumberSt(String phoneNumberSt) {
        this.phoneNumberSt = phoneNumberSt;
    }
    public boolean isSexSt() {
        return this.sexSt;
    }
    
    public void setSexSt(boolean sexSt) {
        this.sexSt = sexSt;
    }
    public String getAddressSt() {
        return this.addressSt;
    }
    
    public void setAddressSt(String addressSt) {
        this.addressSt = addressSt;
    }
    public String getImageSt() {
        return this.imageSt;
    }
    
    public void setImageSt(String imageSt) {
        this.imageSt = imageSt;
    }
    public Set getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set grades) {
        this.grades = grades;
    }




}


