package entity;
// Generated Aug 11, 2020 12:45:06 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String position;

    public Users() {
    }

    public Users(String username, String password, String position) {
        this.username = username;
        this.password = password;
        this.position = position;
    }
    
    

    public Users(int id, String username, String password, String position) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.position = position;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


